#define ARGUMENT                        1
#define REDIRECT_INPUT_FROM_FILE        2
#define REDIRECT_INPUT_FROM_FILE_DESCRIPTOR  3
#define REDIRECT_OUTPUT_TO_FILE         4
#define REDIRECT_OUTPUT_TO_FILE_DESCRIPTOR  5
#define REDIRECT_OUTPUT_APPEND_TO_FILE  6
#define REDIRECT_OUTPUT_APPEND_TO_FILE_DESCRIPTOR  7
#define PIPE                            8
#define OR                              9
#define AND                            10
#define BACKGROUND                     11
#define SEMICOLON                      12
